name: Docker Deployment
author: Al-waleed Shihadeh <wshihadeh.dev@gmail.com>
description: A GitHub Action that supports docker-compose and Docker Swarm deployments
inputs:
  remote_docker_host:
    description: Remote Docker host ie (user@host)
    required: true
  ssh_public_key:
    description: Remote Docker SSH public key
    required: true
  ssh_private_key:
    description: SSH private key used to connect to the docker host
    required: true
  stack_file_name:
    description: Docker stack file used. Default is docker-compose.yaml
    required: false
  docker_prune:
    description: A boolean input to trigger docker prune command.
    required: false
  project_name:
    description: Set project name.
    required: true

runs:
  using: docker
  image: Dockerfile

branding:
  icon: send
  color: green

